// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdznwxispnuzfwotaxgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkem53eGlzcG51emZ3b3RheGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3MTIzMjIsImV4cCI6MjA4OTI4ODMyMn0.fuHClmDNJLsUfl5JT3sqr_1_EfsEIdXK1uw1Qcch5Ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const isSupabaseConfigured = () => !!SUPABASE_URL && !!SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});